<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
<title>src/java/util/ConcurrentModificationException.java</title>
<meta name="robots" content="noindex,nofollow">
<meta name="generator" content="GLOBAL-6.6.3">
<meta http-equiv="Content-Style-Type" content="text/css">
<link rel="stylesheet" type="text/css" href="../style.css">
</head>
<body>
<a id="TOP" name="TOP"></a><div class="comment">
/* [&lt;][&gt;][^][v][top]<a href="#BOTTOM">[bottom]</a><a href="../mains.html">[index]</a><a href="../help.html">[help]</a> */</div>
<hr>
<pre>
<div class="comment">
  Copyright (c) 1997, 2013, Oracle and/or its affiliates. All rights reserved.
  ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.</div>
<a id="L25" name="L25"></a>  25 
<a id="L26" name="L26"></a>  26 <strong class="reserved">package</strong> <a href="../S/3625.html#L43" title="Defined at 43 in src/javax/management/remote/rmi/RMIConnectionImpl_Stub.java.">java</a>.util;
<a id="L27" name="L27"></a>  27 
<div class="comment">
  This exception may be thrown by methods that have detected concurrent
  modification of an object when such modification is not permissible.
  <p>
  For example, it is not generally permissible for one thread to modify a Collection
  while another thread is iterating over it.  In general, the results of the
  iteration are undefined under these circumstances.  Some Iterator
  implementations (including those of all the general purpose collection implementations
  provided by the JRE) may choose to throw this exception if this behavior is
  detected.  Iterators that do this are known as <i>fail-fast</i> iterators,
  as they fail quickly and cleanly, rather that risking arbitrary,
  non-deterministic behavior at an undetermined time in the future.
  </p><p>
  Note that this exception does not always indicate that an object has
  been concurrently modified by a <i>different</i> thread.  If a single
  thread issues a sequence of method invocations that violates the
  contract of an object, the object may throw this exception.  For
  example, if a thread modifies a collection directly while it is
  iterating over the collection with a fail-fast iterator, the iterator
  will throw this exception.
  </p><p>Note that fail-fast behavior cannot be guaranteed as it is, generally
  speaking, impossible to make any hard guarantees in the presence of
  unsynchronized concurrent modification.  Fail-fast operations
  throw <code>ConcurrentModificationException</code> on a best-effort basis.
  Therefore, it would be wrong to write a program that depended on this
  exception for its correctness: <i><code>ConcurrentModificationException</code>
  should be used only to detect bugs.</i>
  @author  Josh Bloch
  @see     Collection
  @see     Iterator
  @see     Spliterator
  @see     ListIterator
  @see     Vector
  @see     LinkedList
  @see     HashSet
  @see     Hashtable
  @see     TreeMap
  @see     AbstractList
  @since   1.2</p></div>
<a id="L70" name="L70"></a>  70 <strong class="reserved">public</strong> <strong class="reserved">class</strong> <a href="../R/1632.html" title="Multiple referred from 136 places.">ConcurrentModificationException</a> <strong class="reserved">extends</strong> <a href="../S/1723.html#L43" title="Defined at 43 in src/java/lang/RuntimeException.java.">RuntimeException</a> <em class="brace">{</em>
<a id="L71" name="L71"></a>  71     <strong class="reserved">private</strong> <strong class="reserved">static</strong> <strong class="reserved">final</strong> <strong class="reserved">long</strong> serialVersionUID = -3666751008965953603L;
<a id="L72" name="L72"></a>  72 
<div class="comment">
      Constructs a ConcurrentModificationException with no
      detail message.</div>
<a id="L77" name="L77"></a>  77     <strong class="reserved">public</strong> ConcurrentModificationException() <em class="brace">{</em>
<a id="L78" name="L78"></a>  78     <em class="brace">}</em>
<a id="L79" name="L79"></a>  79 
<div class="comment">
      Constructs a <code>ConcurrentModificationException</code> with the
      specified detail message.
      @param message the detail message pertaining to this exception.</div>
<a id="L86" name="L86"></a>  86     <strong class="reserved">public</strong> ConcurrentModificationException(<a href="../D/8419.html" title="Multiple defined in 2 places.">String</a> <a href="../D/27673.html" title="Multiple defined in 6 places.">message</a>) <em class="brace">{</em>
<a id="L87" name="L87"></a>  87         <strong class="reserved">super</strong>(<a href="../D/27673.html" title="Multiple defined in 6 places.">message</a>);
<a id="L88" name="L88"></a>  88     <em class="brace">}</em>
<a id="L89" name="L89"></a>  89 
<div class="comment">
      Constructs a new exception with the specified cause and a detail
      message of <code>(cause==null ? null : cause.toString())</code> (which
      typically contains the class and detail message of <code>cause</code>.
      @param  cause the cause (which is saved for later retrieval by the
              {@link Throwable#getCause()} method).  (A <code>null</code> value is
              permitted, and indicates that the cause is nonexistent or
              unknown.)
      @since  1.7</div>
<a id="L101" name="L101"></a> 101     <strong class="reserved">public</strong> ConcurrentModificationException(<a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> cause) <em class="brace">{</em>
<a id="L102" name="L102"></a> 102         <strong class="reserved">super</strong>(cause);
<a id="L103" name="L103"></a> 103     <em class="brace">}</em>
<a id="L104" name="L104"></a> 104 
<div class="comment">
      Constructs a new exception with the specified detail message and
      cause.
      <p>Note that the detail message associated with <code>cause</code> is
      <i>not</i> automatically incorporated in this exception's detail
      message.
      @param  message the detail message (which is saved for later retrieval
              by the {@link Throwable#getMessage()} method).
      @param  cause the cause (which is saved for later retrieval by the
              {@link Throwable#getCause()} method).  (A <code>null</code> value
              is permitted, and indicates that the cause is nonexistent or
              unknown.)
      @since 1.7</p></div>
<a id="L121" name="L121"></a> 121     <strong class="reserved">public</strong> ConcurrentModificationException(<a href="../D/8419.html" title="Multiple defined in 2 places.">String</a> <a href="../D/27673.html" title="Multiple defined in 6 places.">message</a>, <a href="../S/1726.html#L114" title="Defined at 114 in src/java/lang/Throwable.java.">Throwable</a> cause) <em class="brace">{</em>
<a id="L122" name="L122"></a> 122         <strong class="reserved">super</strong>(<a href="../D/27673.html" title="Multiple defined in 6 places.">message</a>, cause);
<a id="L123" name="L123"></a> 123     <em class="brace">}</em>
<a id="L124" name="L124"></a> 124 <em class="brace">}</em>
</pre>
<hr>
<div class="comment">
/* [&lt;][&gt;][^][v]<a href="#TOP">[top]</a>[bottom]<a href="../mains.html">[index]</a><a href="../help.html">[help]</a> */</div>
</body></html>